### PR TITLE
Write macOS friendly dependency installation docs

### LINKED ISSUE #141: MacOS friendly dependency installation guide
The project's step-by-step dependencies installation should also cover up macOS operating system's command lines.

### PR DESCRIPTION
**Pull request by benireni**
Make our project more easily used in other operating systems.

Closes https://github.com/courselab/snaskii22/issues/141

### CODE REVIEW

**Review by vitorfrois — CHANGES_REQUESTED** [review]
commit the same changes on develop branch

**Comment by benireni** [comment]
Development pr in https://github.com/courselab/snaskii22/pull/143

**Comment by benireni** [comment]
> Development pr in #143

Merged

**Review by vitorfrois — APPROVED** [review]

**Review by ImLusca — APPROVED** [review]
LGTM

**Pull request merged**
