### PR TITLE
Bug/#48/check wrong spawn

### PR DESCRIPTION
**Pull request by AnaClaraAmorim**
Prevent energy blocks from spawning in the head of the snake

### CODE REVIEW

**Comment by AnaClaraAmorim** [comment]
Blocked by #47

**Comment by AnaClaraAmorim** [comment]
#48

**Review by XDyao — APPROVED** [review]
It seems OK to me.

**Comment by gp2112** [comment]
Please, commit this as a fix to `feat/#46/spawn-energy-block` branch

**Pull request closed without merging**
