### PR TITLE
Fix codestyle and basic modularization

### PR DESCRIPTION
**Pull request by pedrolmcastro**
# C Standard

The _configure.ac_ file was changed to add the _-std=gnu99_ flag that changes to the GNU99 standard equivalent to the C99 standard with the GNU libraries

# Remove excessive comments

Most of the comments that did not add any new information were removed, prioritazing longer and more detailed names (**NROWS** became **SCENE_ROWS** and **NCOLS** is now **SCENE_COLUMNS**) and commets that remained now use `//` instead of `/**/` if they are composed by a single line

# Consistent indentation

All the indentation was changed to use tabs, this way each contributor can set it's prefered tab size view and nothing will be missaligned, it is important to keep it with tabs only from now on

# Naming conventions

### Consistent snake_case

Multiple functions and variables were in smallcase like the c standard libraries, the intended convention though was snake_case, so `clearscene()` became `clear_scenes()` and `playgame()` is now `play_game()`. Some renames were made to better align with the function purpose, `readscenes()` is now `load_scenes()` and `userinputs()` is now `get_inputs()`

### UPPER_CASE enums

The direction_t enum was changed so that it's constants (**UP**, **DOWN**, **LEFT** and **RIGHT**) are now in UPPER_CASE to align with the style of the \#define constants

### PascalCase structs

The struct naming convention was changed from snake_case_st to PascalCase to avoid confusion with the snake_case_t convention used in the typedefs

# Modularization

The main _snaskii.c_ file was made smaller by creating the _scene.c/scene.h_ files to handle scene functions like clearing, loading and drawing, the _movie.c/movie.h_ files to put the intro movie animation functionalities and the _times.c/times.h_ to create a times_t struct to deal with the times showed in the menu (start time, last frame time and ellapsed time)

### Space to skip initial movie

In the process of breaking the source file, the `go_on` variable became the `playing_game` and `playing_movie` varibles in _snaskii.c_ and _movie.c_ respectively, this changed a little the action of skipping the intro movie, now the space bar skips the movie, while the Q key quits the whole program, even if it is in the intro movie

### Draw scene and menu

The function that was called `show_scene()` does not exist anymore, since it only called `draw_scene()` and then drawed the menu, but this was made depending on a parameter flag, now the `draw_menu()` is an independent function

# Ncurses input/output functions

The input and output functions that come after `initscr()` from _ncurses.h_ now are ncurses functions, `getchar()` changed to `getch()`, `printf()` became `printw()` and `putchar()` is now `addch()`. This was done because is the intended use of the library API and avoids some problems

### CODE REVIEW

**Review by CerqueiraMatheus — APPROVED** [review]
Solid work. The repo looks much more consistent now.

**Review by gp2112 — COMMENTED** [review]
Nice! Is there a reason to heave this [README](https://github.com/courselab/snaskii22/blob/459e6a45265af5b3941936d9795942ffe8886177/README) empty?

**Review by mairacanal — CHANGES_REQUESTED** [review]
Could you please rebase your branch to avoid the commit "[Merge current develop branch](https://github.com/courselab/snaskii22/pull/43/commits/459e6a45265af5b3941936d9795942ffe8886177)"? This commit is misleading as you didn't write the changes that the commit has. If you rebase your branch, the history will be cleaner.

**Review by monacofj — APPROVED** [review]
Excellent work!!
I'm personally not fond of mixing PascalCase with traditional C snake_case (old school tradition devotee). But whatever the community prefers.

**Comment by CerqueiraMatheus** [comment]
Changed the commit message in order to describe what changed and removed unused README

**Comment by mairacanal** [comment]
I didn't get the "Remove unused file" commit... From what I can see, the README file doesn't exist on the `develop` branch. Check: https://github.com/courselab/snaskii22/tree/develop

**Comment by pedrolmcastro** [comment]
I first tried rebasing this branch to create this PR, but I am having some problems with the tool I use to work with git in my local machine and the files were getting messed up when I tried to accept the correct diffs, since this PR changes a lot in code I think it should be incorporated as soon as possible, before it leads to more conflicts and so I merged develop to this branch in the third commit instead. The issue of its non helpful message was corrected by @CerqueiraMatheus I believe.

Now, about the **README** file, it existed in the [develop commit](https://github.com/courselab/snaskii22/tree/8c3ade11cf6c7f0429c3eaea02f44938bc86c5be) branched to become this one with a single line pointing at the **README.md** file, it is like this in the first two commits in this branch, in the [third commit](https://github.com/courselab/snaskii22/tree/a734e69c162a212d47f5d9ad0d962b0a52b25440) I did thought, merging the develop branch to this one, one of the diffs was that this file was removed from develop. The problem is that the tool I use, for some reason, when resolving this creates the removed file again but empty, I noticed this for the **utils.c** that I removed in this branch and manually fixed in the same commit with `git rm`, but I did not noticed the empty **README** file so it ended up commited by mistake, I don't see a problem now though since it was latter removed in this [@CerqueiraMatheus commit](https://github.com/courselab/snaskii22/tree/af19478cc02742ab855297ce829e7b46ebf2b2d0).

**Comment by mairacanal** [comment]
You can try:
```
$ git checkout tidy/#9/codestyle
$ git rebase develop
```
and resolve the conflicts. Then, the git history will be cleaner and really reflect the changes you made.

If you have any difficulty performing the rebase, let me know and I can do it. But I believe it would be a nice git pratice!

**Comment by pedrolmcastro** [comment]
This PR has a [update version](https://github.com/courselab/snaskii22/pull/63)

**Pull request closed without merging**
