### PR TITLE
make snake movement

### LINKED ISSUE #18: make the snake move
Currently the snake doesn't move at all. To start creating the game logic the first thing needed would be the snake movement.

### PR DESCRIPTION
**Pull request by Grillo-0**
The snake was static and part of the background.

This PR make the movement of the snake possible. it implement a
queue and to move, it remove the tail and place it on the front with
its position updated based on the snake's direction.

To make the control and drawing of the snake, the snake was made a
global variable.

Also make snake growth possible.

Fixes #18

### CODE REVIEW

**Comment by Grillo-0** [comment]
I will mark this PR as ready when #52 is merged

**Comment by vrrusso** [comment]
I tried to build this branch and was not possible. It seems it uses the old make install that did not work.

**Comment by Grillo-0** [comment]
> I tried to build this branch and was not possible. It seems it uses the old make install that did not work.

Strange, here it works fine.

**Comment by pedro-rs** [comment]
Movement works nicely here. 
However, when I crashed into the wall I got a "1944 segmentation fault".
In addition to that, there is something making it look as if, when moving in a vertical direction, the snake's speed is faster than when moving in a horizontal direction.

**Review by pedro-rs — CHANGES_REQUESTED** [review]
Prevent sudden change in directions.

**Review by pedro-rs — APPROVED** [review]
LGTM. Let's work on fixing border collision and vertical/horizontal speeds next.

**Pull request merged**
