### PR TITLE
Fix spelling mistake in README.md

### PR DESCRIPTION
**Pull request by Jacques-Murray**
Fixed misspelling of "arena" in README.md

For issue #32

### CODE REVIEW

**Review by AnaClaraAmorim — APPROVED** [review]

**Review by PauloMRocha — APPROVED** [review]
Spelling mistake corrected. Approved!

**Comment by mairacanal** [comment]
Could you please change the base of this PR? Currently, the base is the `main` and it should be `develop`

**Comment by Jacques-Murray** [comment]
Changes to develop branch.

**Comment by monacofj** [comment]
Great @Jacques-Murray !!!
A warm welcome!

**Comment by Jacques-Murray** [comment]
Thank you.

**Pull request merged**
