### PR TITLE
Tidy/#15/rename doc

### PR DESCRIPTION
**Pull request by monacofj**
This changes `doc` to `docs` to address #15

### CODE REVIEW

**Comment by Math-42** [comment]
Please, merge this pull request to the develop branch.

**Comment by CerqueiraMatheus** [comment]
I think that a solution, in order to solve #15 and follow what @Math-42 requested, is to [change the project default branch](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch) to the `develop`, at least while a new version isn't released. However, it isn't clear to me if it can have any side effects.

**Review by gp2112 — CHANGES_REQUESTED** [review]
@monacofj if you want to merge just your last commit to main branch, I think it would be better if you rebased this branch first

```bash
git rebase --onto main develop tidy/#15/rename-doc
```

**Comment by CerqueiraMatheus** [comment]
Closed for hotfix

**Pull request closed without merging**
